data: '/home/linjunyang/en_vi/data/'
logF: 'experiments/en_vi/'
epoch: 120
batch_size: 64
optim: 'adam'
cell: 'lstm'
attention: 'luong_gate'
learning_rate: 0.0003
max_grad_norm: 10
learning_rate_decay: 0.8
start_decay_at: 12
emb_size: 512
hidden_size: 512
dec_num_layers: 2
enc_num_layers: 2
bidirectional: True
dropout: 0.4
max_time_step: 50
eval_interval: 1000
save_interval: 3000
metrics: ['bleu']
shared_vocab: False
beam_size: 4
unk: False
schedule: False
schesamp: False
length_norm: True